---
title: "alignment_error_function_CZ"
author: "Crystal Zang"
date: "4/22/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(hdf5r)
library(dplyr)
library(readr)
library(rlang)
library(cranium)
library(broom)
library(tidyverse)
library(gridExtra)
library(mosaic)

#new packages
library(sjstats)
library(grDevices)
library(skimr)
```


# Compare error A for two wt thresholds:
0.9: #error = 6
0.6: #error = 5
```{r}
correctionA_wt_0.9 <- read_csv("correction_results/correctionA_wt_0.9.csv")%>%
  select(-X1)
correctionA_wt_0.6 <- read_csv("correction_results/correctionA_wt_0.6.csv")%>%
  select(-X1)

path = "Sample/WildType"
file_names <- list.files(path, pattern=".h5", full.names=TRUE)


correctionA_wt_0.9_y <- correctionA_wt_0.9 %>%
  filter(y_flipped == 1)
for (i in (1:length(correctionA_wt_0.9_y))){
  j=Sample_id
  c_ro_tidy_brain <- file_names[j]%>%
    read_h5()%>%
    tidy(type, threshold = threshold.n)%>%
    reorient(correctionA=TRUE)
}

ro_tidy_brain<-file_names[j]%>%
    read_h5()%>%
    tidy(type, threshold = threshold.n)%>%
    reorient()

data<-read_h5(file_names[20])

errorA.brain(data)
class(data)
```


# Error B 
```{r}
path = "Sample/YouToo"
path = "Sample/WildType"
file_names <- list.files(path, pattern=".h5", full.names=TRUE)

#youtoo sample
data<-read_h5(file_names[5])%>%
  tidy(threshold=0.9)%>%
  reorient()

brain<-read_h5(file_names[5])

tidy_brain <- brain%>%
  tidy(threshold=0.6)

ro_tidy_brain<-tidy_brain%>%
  reorient()
attr(ro_tidy_brain, "linear_mod_yz")


##wt
brain_wt_2<-read_h5(file_names[2])

tidy_brain_wt_2 <- brain_wt_2%>%
  tidy(threshold=0.9)

ro_tidy_brain_wt_2 <- tidy_brain_wt_2%>%
  reorient()

att_lm<-attr(ro_tidy_brain_wt_2, "linear_mod")
att_quad<-attr(ro_tidy_brain_wt_2, "quad_mod")


summary(att_lm)
summary(att_quad)
lm.intercept = round((summary(att_lm)$coefficients["(Intercept)", "Estimate"]), 4)
lm.slope = round((summary(att_lm)$coefficients["x", "Estimate"]), 10)
quad.slope = round((summary(att_quad)$coefficients["I(x^2)", "Estimate"]), 5)

plot2d(data)

z_statistics<-ro_tidy_brain%>%
  skim(z)%>%
  select(stat, formatted)%>%
  spread(stat, formatted)

y_statistics<-data%>%
  skim(y)%>%
  select(stat, formatted)%>%
  spread(stat, formatted)

#LOOP

errorB_df <- data.frame()

#function
#########start of function
#apply qmodel to all sample, testing for each threshold
is.z.curve<- function(data, type="wildtype", threshold.n=0.9) UseMethod("is.z.curve")


is.z.curve.brain <- function(data, type="wildtype", threshold.n=0.9){
    ro_tidy_brain <- data%>%
        tidy(threshold=threshold.n)
    is_errorB(ro_tidy_brain, type = "wildtype", threshold=0.9)
    return(sum_tb)
}

is.z.curve.tbl_brain <- function(data, type="wildtype", threshold.n=0.9){
    ro_tidy_brain <- data %>%
        reorient()
    z_mean <- ro_tidy_brain %>%
        skim(z)%>%
        select(stat, formatted)%>%
        spread(stat, formatted)%>%
        pull(mean)
    
    #Fit models after reorient
    lm_model <- attr(ro_tidy_brain, "linear_mod") #linear model y = x
    quad_model <- attr(ro_tidy_brain, "quad_mod") #quadratic model y = x^2 + x
    
    sum_tb <- data.frame(threshold = threshold.n)%>%
          mutate(z_mean = z_mean)%>%
          #linear model: intercept and slope
          mutate(lm.intercept = round((summary(lm_model)$coefficients["(Intercept)", "Estimate"]), 4)) %>%
          mutate(lm.slope = round((summary(lm_model)$coefficients["x", "Estimate"]), 10))%>%
          #quad model: slope
          mutate(quad.slope = round((summary(quad_model)$coefficients["I(x^2)", "Estimate"]), 5))
    return(sum_tb)
}

is.z.curve.tbl_brain(ro_tidy_brain)
#########end of function

mean <- mean%>%
  as.numeric()

is_errorB.tbl_brain(tidy_brain)

mean <- data%>%
        reorient()%>%
        skim(z)%>%
        select(stat, formatted)%>%
        spread(stat, formatted)%>%
        pull(mean)




is_errorB.brain <- function(data, type="wildtype", threshold.n=0.9){
  ro_tidy_brain <- data%>%
    tidy(type, threshold = threshold.n)%>%
    reorient()
  ro_model <- attr(ro_tidy_brain, "linear_mod")  #model applied on reoriented data
  quad.coeff = round((summary(ro_model)$coefficients["I(x^2)", "Estimate"]), 4)

  if (quad.coeff < 0) {
    message("Y Axis is flipped")
    return(TRUE)
  } else{
    message("Correct alignment")
    return(FALSE)
  }
}

```


```{r}
curve_wt_0_6 <- read_csv("correction_results/curve_wt_0.6.csv")%>%
  select(-X1) %>%
   mutate(type = "wildtype")
curve_yt_0_6 <- read_csv("correction_results/curve_yt_0.6.csv")%>%
  select(-X1)%>%
  mutate(type = "youtoo")

curve_all_0.6 <- rbind(curve_wt_0_6, curve_yt_0_6)

mplot(curve_all_0.6)
```


#curve at xz plane
```{r}


#identify curve at xz plot
ggplot( data = curve_all_0.6, aes(x = quad.slope_xz)) + geom_histogram(binwidth = 0.0033) + facet_wrap(~type, ncol = 4) + labs(title = "Quadratic slope for xz plane") 

favstats(curve_wt_0_6$quad.slope_xz)
favstats(curve_yt_0_6$quad.slope_xz)

mplot(curve_all_0.6)

#wt normal range for quadratic slope in xz plane
Q3 <- quantile(curve_wt_0_6$quad.slope_xz, 0.75) 
Q1 <- quantile(curve_wt_0_6$quad.slope_xz, 0.25)
IQR = Q3-Q1
normal_range_lb = Q1-1.5*IQR
normal_range_ub = Q3+1.5*IQR
class(normal_range_ub)
normal_range<-c(normal_range_lb,normal_range_ub)
normal_range

curve_all_0.6_curve <- curve_all_0.6 %>%
  mutate(is_curve = if_else(quad.slope_xz < -0.00202 | quad.slope_xz > 0.00182, "curve", "not curve"))

mplot(curve_all_0.6_curve)

tb<-curve_all_0.6_curve%>%
  group_by(type, is_curve)%>%
  summarize(N=n())

yt_curve<- curve_all_0.6_curve%>%
  filter(is_curve=="curve")
yt_not_curve<- curve_all_0.6_curve%>%
  filter(type=="youtoo" & is_curve=="not curve")


# test is_errorB function
is_errorB

path = "Sample/WildType"
file_names <- list.files(path, pattern=".h5", full.names=TRUE)

#youtoo sample
brain_wt_1<-read_h5(file_names[1])
tidy_brain_wt_1 <- tidy(brain_wt_1, threshold.n=0.6)
plot3d(tidy_brain_wt_1)

if (is_errorB(data, threshold.n=0.6)==FALSE){
  message("you are right")
}else{
  message("bye")
}

```

# degrees.to.radians function
```{r}
degrees.to.radians<-function(degrees=45,minutes=30){
    if(!is.numeric(minutes)) stop("Please enter a numeric value for minutes!\n")
    if(!is.numeric(degrees)) stop("Please enter a numeric value for degrees!\n")
        decimal<-minutes/60
        c.num<-degrees+decimal
        radians<-c.num*pi/180
        radians
}
# example
degrees.to.radians(degrees=90)
```


# Correction for errorB
```{r}
path = "Sample/YouToo"

path = "Sample/WildType"
file_names <- list.files(path, pattern=".h5", full.names=TRUE)

brain_yt_334 <-read_h5(file_names[29])
brain_wt_03 <-read_h5(file_names[3])

tidy_brain_yt_334<- tidy.brain(brain_yt_334, threshold.n = 0.75)
tidy_brain_wt_03<- tidy.brain(brain_wt_03, threshold.n = 0.6)


ro_tidy_brain_yt_334 <- reorient(tidy_brain_yt_334)
ro_tidy_brain_wt_03 <- reorient(tidy_brain_wt_03)

plot2d(ro_tidy_brain_yt_334)

rgl::plot3d(ro_tidy_brain_yt_334)

favstats(ro_tidy_brain_yt_334$x)
is_errorA(brain_yt_01, threshold.n = 0.6)
#FALSE

rgl::plot3d(ro_tidy_brain_yt_01)

degree_input = 300
n <- nrow(ro_tidy_brain_yt_334)
n
matrix <- matrix(0, nrow=n, ncol=n)
dim(matrix)

for (i in (1:n)){
  matrix[i,i] = 1
  matrix[1,1] <- cos(degrees.to.radians(degrees=degree_input))
  matrix[1,2] <- -sin(degrees.to.radians(degrees=degree_input))
  matrix[2,1] <- sin(degrees.to.radians(degrees=degree_input))
  matrix[2,2] <- cos(degrees.to.radians(degrees=degree_input))
}
matrix[10,10]

ro_tidy_brain_yt_334_xyz<-ro_tidy_brain_yt_334%>%
  select(x,y,z)%>%
  t()

yt_334_freq <- ro_tidy_brain_yt_334%>%
  select(Freq,gray_val)
  
dim(ro_tidy_brain_yt_334_xyz)
dim(matrix)

C <- ro_tidy_brain_yt_334_xyz %*% matrix 


D <- t(C)
dim(D)
class(D)
D <- as.data.frame(D)

D_freq <- cbind(D, yt_334_freq)

#colnames(D)[colnames(D) == "D"] <- "x"

class(D_freq) <- append("tbl_brain", class(D_freq)) 
mean(D_freq$x)

plot2d(D_freq)


rgl::plot3d(D_freq)

is_z_curve(D,type = "youtoo", threshold.n = 0.6)


class(ro_tidy_brain_wt_03)
plot2d(ro_tidy_brain_yt_01)

```


