---
title: "model_eval"
author: "CZ"
date: "4/9/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(hdf5r)
library(dplyr)
library(rlang)
library(cranium)
library(broom)
library(tidyverse)
library(gridExtra)
library(mosaic)

#new packages
library(sjstats)
```

# Tidy Function (Final:4/9, 4:30 pm)
```{r}
tidy.brain <- function(x, type="wildtype", threshold.n=0.9, ...) {
  if (type=="youtoo"){
      if(threshold.n != 0.9){
        threshold = threshold.n   
        print(paste0("Set threshold: ", threshold))
      }else{
        threshold = 0.5
        print("Default You-Too threshold: 0.5")
      }
  }else{
      if(threshold.n != 0.9) {  #if threshold is not default, use the input threshold
        threshold = threshold.n 
        print(paste0("Set threshold: ", threshold))
      }else{
        threshold = 0.9
        print(("Default threshold: 0.9"))
      }
  }
    res <- x %>%
    as.data.frame.table() %>%
    mutate(x = as.integer(Var1) * 0.13,
           y = as.integer(Var2) * 0.13,
           z = as.integer(Var3) * 0.21) %>%
    select(x, y, z, Freq) %>%
    tibble::as_tibble() %>%
    mutate(gray_val = grDevices::gray(1 - Freq)) %>%
    filter(Freq > threshold)
    class(res) <- append("tbl_brain", class(res))
  return(res)
}

#test
#test<-tidy(brain_ls_wt[[1]], type= "wildtype", threshold.n = 0.9)
```


# Function--model (Final:4/9, 4:30 pm)
Requires: 
1.data to be in brain class type.
2.type to be either "wildtype" or "youtoo"
```{r}
#Fit quadratic model, output is the adjusted r_square
qmodel.brain<- function(data, type="wildtype", threshold.n=0.9){
  if (type == "wildtype"){  
    tidy_brain <- data %>%
    tidy(type="wildtype", threshold = threshold.n )
    ro_tidy_brain<- reorient(tidy_brain)
  }
  if(type== "youtoo"){  
    tidy_brain <- data%>%
    tidy(type="youtoo", threshold = threshold.n)
    ro_tidy_brain<- reorient(tidy_brain)

  }
  model <- lm(y ~ I(x^2) + x, data = tidy_brain) #model applied on original data
  ro_model <- attr(ro_tidy_brain, "quad_mod")  #model applied on reoriented data
  mean.fitted = mean(ro_model$fitted.values)
  #sigma=sjstats::rse(ro_model). RSE: residual standard error
  #RSE = sjstats::rse(ro_model)
  sum_tb<- ro_model %>%
    broom::glance() %>%
    mutate(num.signal = nrow(tidy_brain),
           adj.r.squared.original = round(summary(model)$adj.r.squared, 3),#original r square
           quad.coeff = round(summary(ro_model)$coefficients[3, 1],4),
           RMSE = sjstats::rmse(ro_model) ) 
  return(sum_tb)
}

#test
#sum_tb <- qmodel.brain(data=brain_ls_youtoo[[2]], type= "youtoo")
#qmodel.brain(data=brain_ls_wt[[1]], type= "wildtype", threshold.n = 0.1)
#qmodel.brain(data=brain_ls_wt[[1]], type= "wildtype")

```

#Combine files
```{r}
# qmodel_sum_tb_wt_1 <- read_csv("visualization_results/qmodel_sum_tb_wt.1.csv")
# qmodel_sum_tb_wt_2 <- read_csv("visualization_results/qmodel_sum_tb_wt.2.csv")
# 
# qmodel_sum_tb_wt_3 <- read_csv("visualization_results/qmodel_sum_tb_wt.3.csv")
# qmodel_sum_tb_wt_4 <- read_csv("visualization_results/qmodel_sum_tb_wt.4.csv")

#qmodel_sum_tb_wt <- rbind(qmodel_sum_tb_wt_1,qmodel_sum_tb_wt_2, qmodel_sum_tb_wt_3,qmodel_sum_tb_wt_4)

#write.csv(qmodel_sum_tb_wt, file = "visualization_results/qmodel_sum_tb_wt .csv", row.names=F)
```

```{r}
qmodel_sum_tb_wt <- read_csv("visualization_results/qmodel_sum_tb_wt.csv")
qmodel_sum_tb_youtoo <- read_csv("visualization_results/qmodel_sum_tb_youtoo.1.csv")
```

```{r}
mplot(qmodel_sum_tb_wt)

#num signals
ggplot( data = qmodel_sum_tb_wt, aes(x = num.signal)) + geom_histogram(binwidth = 5100) + labs(title = "Wild Type: number of signals captured")+ 
  theme(axis.text.x = element_text(size=13),
          axis.text.y = element_text(size=13),
          axis.title = element_text(size = 15, face= "bold"))

#adj r2
ggplot( data = qmodel_sum_tb_wt, aes(x = adj.r.squared)) + geom_histogram(binwidth = 0.011) + labs(title = "Adjusted R square for 43 Wild Type Sample")

#RMSE
ggplot( data = qmodel_sum_tb_wt, aes(x = RMSE)) + geom_histogram(binwidth = 0.14) + labs(title = "RMSE for 43 Wild Type Sample") 

#adj r2 + RMSE + num signals
ggplot(data = qmodel_sum_tb_wt, aes(x = adj.r.squared, y = RMSE)) + geom_point()  + aes(colour = num.signal) + theme(legend.position = "right") + 
  theme(axis.text.x = element_text(size=18),
          axis.text.y = element_text(size=18),
          axis.title = element_text(size = 18, face= "bold"),
          legend.text=element_text(size=13),
          legend.title=element_text(size=18, face="bold"))+
   labs(title = "Wild Type: Relationship between Adj.R2, RMSE and number of signals depicted")

#Number of signals and RMSE
ggplot(data = qmodel_sum_tb_wt, aes(x = num.signal, y = adj.r.squared)) + geom_point()  + labs(title = "Wild Type: Relationshop between number of signals and RMSE") +
   theme(axis.text.x = element_text(size=13),
          axis.text.y = element_text(size=18),
          axis.title = element_text(size = 18, face= "bold"),
          legend.text=element_text(size=13),
          legend.title=element_text(size=18, face="bold"))
```

#You Too
```{r}
#mplot(qmodel_sum_tb_youtoo)


#num signals
ggplot( data = qmodel_sum_tb_youtoo, aes(x = num.signal)) + geom_histogram(binwidth = 59) + labs(title = "You Too: number of signals captured")+ 
  theme(axis.text.x = element_text(size=13),
          axis.text.y = element_text(size=13),
          axis.title = element_text(size = 15, face= "bold"))

#adj r2
ggplot( data = qmodel_sum_tb_youtoo, aes(x = adj.r.squared)) +  geom_histogram(binwidth = 0.028) + labs(title = "Adjusted R square for 35 You Too Sample")

#RMSE
ggplot( data = qmodel_sum_tb_youtoo, aes(x = RMSE)) +  geom_histogram(binwidth = 0.33) + labs(title = "RMSE for 35 You Too Sample") 


#adj r2 + RMSE + num signals
ggplot(data = qmodel_sum_tb_youtoo, aes(x = adj.r.squared, y = RMSE)) +   geom_point()  +
  aes(colour = num.signal) + 
  theme(legend.position = "right") + 
  theme(axis.text.x = element_text(size=18),
          axis.text.y = element_text(size=18),
          axis.title = element_text(size = 18, face= "bold"),
          legend.text=element_text(size=13),
          legend.title=element_text(size=18, face="bold"))+
  labs(title = "You Too: Relationship between Adj.R2, RMSE and number of signals depicted")


#Number of signals and RMSE
ggplot(data = qmodel_sum_tb_youtoo, aes(x = num.signal, y = adj.r.squared)) + geom_point()  + labs(title = "You Too: Relationshop between number of signals and RMSE") +
   theme(axis.text.x = element_text(size=13),
          axis.text.y = element_text(size=18),
          axis.title = element_text(size = 18, face= "bold"),
          legend.text=element_text(size=13),
          legend.title=element_text(size=18, face="bold"))




```


```{r}
qmodel_sum_tb_youtoo_2 <- qmodel_sum_tb_youtoo%>%
  mutate(y_flipped = if_else(quad.coeff < 0, "flipped", "correct"))

mplot(qmodel_sum_tb_youtoo_2)

ggplot(data = qmodel_sum_tb_youtoo_2, aes(x = num.signal, y = adj.r.squared)) + geom_point()  + aes(colour = y_flipped) + theme(legend.position = "right") + labs(title = "Identify Alignment Error-Flipped Y-Axis")+
   theme(axis.text.x = element_text(size=13),
          axis.text.y = element_text(size=18),
          axis.title = element_text(size = 18, face= "bold"),
          legend.text=element_text(size=13),
          legend.title=element_text(size=18, face="bold"))
```

```{r}
youtoo_y.flipped <- qmodel_sum_tb_youtoo_2%>%
  filter(y_flipped == "flipped")

youtoo_y.flipped_name<-as.vector(youtoo_y.flipped$sample)
youtoo_y.flipped_name
```




# Read file: You Too. Output class type: brain.
```{r eval=FALSE, include=FALSE}
path = "Sample/YouToo"

file_names <- list.files(path, pattern=".h5", full.names=TRUE)

brain_ls_youtoo.1 <- list()  
name_youtoo.1 <- list()  
file_names.1 <- youtoo_y.flipped_name

for (i in (1:length(file_names.1))) {
  brain_ls_youtoo.1[[i]] <- file_names.1[i] %>%
  read_h5()
  name_youtoo.1[i] <- sub("_Probabilities.h5", "", file_names.1[i])
}


```

```{r}
th_wt <- read_csv("visualization_results/threshold_wt_19.csv")

th_wt_test <- th_wt%>%
  group_by(threshold)%>%
  summarize(r2_avg = mean(adj.r.squared), sd = sd(adj.r.squared))
th_wt$threshold <- as.character(th_wt$threshold)
mplot(th_wt)


th_wt$Sample <- as.character(th_wt$Sample)

gf_point(threshold ~ adj.r.squared, data = th_wt) %>%
gf_facet_wrap(~Sample, ncol = 5) %>% 
gf_labs(title = "", caption = "")
```





