---
title: "model_fit_CZ"
author: "CZ"
date: "4/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(hdf5r)
library(dplyr)
library(rlang)
library(BiocInstaller)
library(rhdf5)
library(cranium)
library(broom)
library(tidyverse)
library(gridExtra)
library(mosaic)
```


# Data: Wild Type 
```{r}
ls_wt <- c("Wild Type_101", "Wild Type_102")
ls_wt

file_ls_wt =c("0")
file_ls_wt

for (i in (1:length(ls_wt))) {
  file_ls_wt[i] = paste("file", ls_wt[i])
}

file_ls_wt

file_ls_wt[1]<- "Sample/AT_wildtype_101_Probabilities.h5"
file_ls_wt[2] <-  "Sample/AT_wildtype_102_Probabilities.h5"
#file_ls[3] <-  "Sample/AT_wildtype_104_Probabilities.h5"



file_ls_wt

#defalt threshol = 0.9
brain_ls_wt <- list()
for (i in (1:length(ls_wt))) {
  brain_ls_wt[[i]] <- file_ls_wt[i] %>%
  read_h5()
}
```


# Data: You too
```{r}
ls_youtoo <- c("You_Too_01", "You_Too_02")

file_ls_youtoo =c("0")
file_ls_youtoo

for (i in (1:length(ls_youtoo))) {
  file_ls_youtoo[i] = paste("file", ls_youtoo[i])
}

file_ls_youtoo

file_ls_youtoo[1] <- "Sample/AT_01_Probabilities.h5"
file_ls_youtoo[2] <- "Sample/AT_02_Probabilities.h5"
#file_ls[6] <- "Sample/AT_03_Probabilities.h5"
#file_ls[7] <- "Sample/AT_04_Probabilities.h5"
#file_ls[8] <- "Sample/AT_06_Probabilities.h5"
#file_ls[9] <- "Sample/AT_21_Probabilities.h5"


file_ls_youtoo
#threshold = 0.7
brain_ls_youtoo <- list()
for (i in (1:length(file_ls_youtoo))) {
  brain_ls_youtoo[[i]] <- file_ls_youtoo[i] %>%
  read_h5()
}

```

# Function--model (Final)
Requires: 
1.data to be in brain class type.
2.type to be either "wildtype" or "youtoo"
```{r}
#Fit quadratic model, output is the adjusted r_square
qmodel.brain<- function(data, type){
  if (type == "wildtype"){
    tidy_brain <- data %>%
  tidy(threshold = 0.9)
    ro_tidy_brain<-tidy_brain%>%
    lapply(reorient)
  }
  if(type== "youtoo"){
    tidy_brain <- data%>%
    tidy(threshold = 0.5)
    ro_tidy_brain<-tidy_brain%>%
    lapply(reorient)
  }
  model <- lm(y ~ I(x^2) + x, data = tidy_brain) #model applied on original data
  r_2 = round(summary(model)$r.squared, 3) #original r square
 # ro_model <- lm(y ~ I(x^2) + x, data = ro_tidy_brain) #model applied on reoriented data
 # ro_r_2 = round(summary(ro_model)$r.squared,3) #reoriented r square

  num_signal = nrow(tidy_brain)
  return(data.frame(type, r_2, num_signal))
  #return(data.frame(type, r_2, ro_r_2, num_signal))
}

qmodel.brain(brain_ls_youtoo[[1]], type="youtoo")

```

# Plot Function 
Take out the linear model
```{r}


#' Plot a slice of a 3D image
#' @inheritParams graphics::image
#' @param z slice of the 3D image to display
#' @importFrom graphics image
#' @export
#' @examples
#' file <- "~/Data/barresi/AT_1_Probabilities.h5"
#' raw <- read_h5(file)
#' image(raw)
#' image(raw, z = 23)


image.brain <- function(x, z = NULL, ...) {
  if (is.null(z)) {
    z <- floor(dim(x)[3] / 2)
  }
  graphics::image(x[,,z])
}

#' Plot a 2D projection of a 3D image
#' @inheritParams plot3d.tbl_brain
#' @param plane a character vector of length 2 indicating the
#' plane to project to (x, y, z)
#' @param show_max Plot the maximum frequency or the average?
#' @export
#' @examples
#' file <- "~/Data/barresi/wildtype/AT/AT_1_Probabilities.h5"
#' \dontrun{
#' tidy_brain <- read_h5(file) %>%
#'   tidy()
#' plot2d(tidy_brain, show_max = TRUE)
#' plot2d(tidy_brain)
#' }

plot2d <- function(x, title, show_max = FALSE, ...) UseMethod("plot2d")

#' @export
#' @rdname plot2d

plot2d.brain <- function(x, title, show_max = FALSE, ...) {
  tidy_brain <- tidy(x)
  plot2d(tidy_brain, show_max = FALSE, ...)
}

#' @export
#' @importFrom gridExtra grid.arrange
#' @rdname plot2d
plot2d.tbl_brain <- function(x, title, show_max = FALSE, ...) {
  gridExtra::grid.arrange(
    plot2d_plane(x, plane = c("x", "z"), show_max, ...),
    plot2d_plane(x, plane = c("x", "y"), show_max, ...),
    plot2d_plane(x, plane = c("y", "z"), show_max, ...),
    nrow = 1,
    top = title
  )
}

#' @export
#' @importFrom rlang !!
#' @import ggplot2
#' @rdname plot2d
plot2d_plane <- function(x, plane = c("x", "z"), show_max = FALSE, ...) {
  depth <- setdiff(c("x", "y", "z"), plane)
  depth_var <- rlang::sym(depth)

  gg_data <- x %>%
    group_by(.dots = plane) %>%
    summarize(N = n(), min_freq = min(Freq),
              avg_depth = mean(!! depth_var, na.rm = TRUE),
              max_depth = max(!! depth_var, na.rm = TRUE))

  if (show_max) {
    plot_var <- "max_depth"
  } else
    plot_var <- "avg_depth"
  labels <- data.frame(var = c("x", "y", "z"),
                       label = c("Lateral (x, microns)",
                                 "Anterior/Posterior (y, microns)",
                                 "Dorsal/Ventral (z, microns)")) %>%
    filter(var %in% plane)
  titles <- data.frame(depth_var = c("x", "y", "z"),
                       title = c("Side View", "Front View", "Top View"))
  ggplot(gg_data, aes_string(x = plane[1], y = plane[2], color = plot_var), ...) +
    geom_point(alpha = 0.1, size = 0.5) +
    geom_smooth(method = "lm", formula = y ~ I(x^2) + x, color = "red") +
   # geom_smooth(method = "lm", color = "red") +
    annotate("text", x = 0, y = 0, label = "origin", size = 5) +
    annotate("text", x = 0, y = 0,
             label = paste0("min_prob: ", round(min(pull(ungroup(gg_data), "min_freq")), 2))) +
    scale_color_continuous(guide = FALSE) +
    scale_x_continuous(filter(labels, var == plane[1])$label) +
    scale_y_continuous(filter(labels, var == plane[2])$label) +
    ggtitle(filter(titles, depth_var == depth)$title)
}

#' Plot a 3D image of a brain
#' @inheritParams rgl::plot3d
#' @export
#' @examples
#' file <- "~/Data/barresi/AT_1_Probabilities.h5"
#' \dontrun{
#' if (require(dplyr)) {
#'   tidy_brain <- file %>%
#'     read_h5() %>%
#'     tidy()
#'   plot3d(tidy_brain)
#' }
#' }

```



# Use qmodel function on the youtoo data
```{r}
model_df <- data.frame()
for (i in (1:length(ls_youtoo))) {
  m <- qmodel.brain(brain_ls_youtoo[[i]], type="youtoo")%>%
          mutate(sample = ls_youtoo[i])
  model_df <- rbind(model_df, m)
}
View(model_df)
```

# Test
```{r}
#Edit tidy function
tidy.brain <- function(x, threshold = 0.9, type = NA, ...) {
  if (type== "wildtype"){
    res <- x %>%
    as.data.frame.table() %>%
    mutate(x = as.integer(Var1) * 0.13,
           y = as.integer(Var2) * 0.13,
           z = as.integer(Var3) * 0.21) %>%
    select(x, y, z, Freq) %>%
    tibble::as_tibble() %>%
    mutate(gray_val = grDevices::gray(1 - Freq)) %>%
    filter(Freq > threshold)
    class(res) <- append("tbl_brain", class(res))
  } 
  if (type=="youtoo"){
    threshold=0.5
    res <- x %>%
    as.data.frame.table() %>%
    mutate(x = as.integer(Var1) * 0.13,
           y = as.integer(Var2) * 0.13,
           z = as.integer(Var3) * 0.21) %>%
    select(x, y, z, Freq) %>%
    tibble::as_tibble() %>%
    mutate(gray_val = grDevices::gray(1 - Freq)) %>%
    filter(Freq > threshold)
    class(res) <- append("tbl_brain", class(res))
  } 
  return(res)
}

#You too data
ls_youtoo <- c("You_Too_01", "You_Too_02")
file_ls_youtoo =c("0")

for (i in (1:length(ls_youtoo))) {
  file_ls_youtoo[i] = paste("file", ls_youtoo[i])
}

file_ls_youtoo[1] <- "Sample/AT_01_Probabilities.h5"
file_ls_youtoo[2] <- "Sample/AT_02_Probabilities.h5"
#file_ls[6] <- "Sample/AT_03_Probabilities.h5"
#file_ls[7] <- "Sample/AT_04_Probabilities.h5"
#file_ls[8] <- "Sample/AT_06_Probabilities.h5"
#file_ls[9] <- "Sample/AT_21_Probabilities.h5"

#Read and tidy
tidy_brain_ls_youtoo <- list()
for (i in (1:length(file_ls_youtoo))) {
  tidy_brain_ls_youtoo[[i]] <- file_ls_youtoo[i] %>%
  read_h5() %>%
 # tidy( threshold=0.5)
  tidy(type="youtoo")
}
#Reorient
ro_brain_ls_youtoo<-tidy_brain_ls_youtoo%>%
lapply(reorient)

#Plot
plotlist_youtoo <- list()
for (i in (1:length(ls_youtoo))){
  plotlist_youtoo[[i]] <- plot2d(ro_brain_ls_youtoo[[i]], title=paste("Sample", ls_youtoo[i]))
   # plot(plotlist[[i]])
   # dev.off
}



model_df <- data.frame()
for (i in (1:length(ls_youtoo))) {
  m <- qmodel.brain(brain_ls_youtoo[[i]], type="youtoo")%>%
          mutate(sample = ls_youtoo[i])
  model_df <- rbind(model_df, m)
}
View(model_df)
```



# Experiment(Old function) 
Generate two tables for wildtype and youtoo for threshold, $r^2$, number of signals comparison.
```{r}

x0 = 0.9
list <- seq(x0, 0.99, 0.03)

#Calculate fitted r square
fit_value<-c()
for (i in (1:length(list))){
   fit_value[i]<- round(model_fit(list[i], brain_ls_youtoo[[1]]),4)
}
fit_value

#Calculate number signals
num_signals<- c()
for (i in (1:length(list))){
   num_signals[i]<- model_num_signal(list[i], brain_ls_wt[[1]])
}
num_signals
  
fitted_threshold_tb <- data.frame(list, fit_value, num_signals)
colnames(fitted_threshold_tb)[1] = "threshold.YouToo"
colnames(fitted_threshold_tb)[2] = "r_square.YouToo"
colnames(fitted_threshold_tb)[3] = "num_signals.YouToo"

df2
fitted_threshold_tb_wt <- data.frame(df2, num_signals)
colnames(fitted_threshold_tb_wt)[1] = "threshold.WT"
colnames(fitted_threshold_tb_wt)[2] = "r_square.WT"
colnames(fitted_threshold_tb_wt)[3] = "num_signals.WT"
```


