---
title: "Plot"
author: "CZ"
date: "4/1/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#hdf5
```


#hdf5r
```{r}
library(hdf5r)
library(dplyr)
library(rlang)
library(BiocInstaller)
#biocLite("rhdf5")
library(rhdf5)
#devtools::install_github("beanumber/cranium")
library(cranium)
library(broom)
library(tidyverse)
library(gridExtra)
library(mosaic)
```

# Edited functions
```{r}
tidy.brain <- function(x, threshold = 0.9, ...) {
  res <- x %>%
    as.data.frame.table() %>%
    mutate(x = as.integer(Var1) * 0.13,
           y = as.integer(Var2) * 0.13,
           z = as.integer(Var3) * 0.21) %>%
    select(x, y, z, Freq) %>%
    tibble::as_tibble() %>%
    mutate(gray_val = grDevices::gray(1 - Freq)) %>%
    #    filter(Freq > 0) %>%
    filter(Freq > threshold)
  class(res) <- append("tbl_brain", class(res))
  return(res)
}


#' Plot a slice of a 3D image
#' @inheritParams graphics::image
#' @param z slice of the 3D image to display
#' @importFrom graphics image
#' @export
#' @examples
#' file <- "~/Data/barresi/AT_1_Probabilities.h5"
#' raw <- read_h5(file)
#' image(raw)
#' image(raw, z = 23)


image.brain <- function(x, z = NULL, ...) {
  if (is.null(z)) {
    z <- floor(dim(x)[3] / 2)
  }
  graphics::image(x[,,z])
}

#' Plot a 2D projection of a 3D image
#' @inheritParams plot3d.tbl_brain
#' @param plane a character vector of length 2 indicating the
#' plane to project to (x, y, z)
#' @param show_max Plot the maximum frequency or the average?
#' @export
#' @examples
#' file <- "~/Data/barresi/wildtype/AT/AT_1_Probabilities.h5"
#' \dontrun{
#' tidy_brain <- read_h5(file) %>%
#'   tidy()
#' plot2d(tidy_brain, show_max = TRUE)
#' plot2d(tidy_brain)
#' }

plot2d <- function(x, title, show_max = FALSE, ...) UseMethod("plot2d")

#' @export
#' @rdname plot2d

plot2d.brain <- function(x, title, show_max = FALSE, ...) {
  tidy_brain <- tidy(x)
  plot2d(tidy_brain, show_max = FALSE, ...)
}

#' @export
#' @importFrom gridExtra grid.arrange
#' @rdname plot2d
plot2d.tbl_brain <- function(x, title, show_max = FALSE, ...) {
  gridExtra::grid.arrange(
    plot2d_plane(x, plane = c("x", "z"), show_max, ...),
    plot2d_plane(x, plane = c("x", "y"), show_max, ...),
    plot2d_plane(x, plane = c("y", "z"), show_max, ...),
    nrow = 1,
    top = title
  )
}

#' @export
#' @importFrom rlang !!
#' @import ggplot2
#' @rdname plot2d
plot2d_plane <- function(x, plane = c("x", "z"), show_max = FALSE, ...) {
  depth <- setdiff(c("x", "y", "z"), plane)
  depth_var <- rlang::sym(depth)

  gg_data <- x %>%
    group_by(.dots = plane) %>%
    summarize(N = n(), min_freq = min(Freq),
              avg_depth = mean(!! depth_var, na.rm = TRUE),
              max_depth = max(!! depth_var, na.rm = TRUE))

  if (show_max) {
    plot_var <- "max_depth"
  } else
    plot_var <- "avg_depth"
  labels <- data.frame(var = c("x", "y", "z"),
                       label = c("Lateral (x, microns)",
                                 "Anterior/Posterior (y, microns)",
                                 "Dorsal/Ventral (z, microns)")) %>%
    filter(var %in% plane)
  titles <- data.frame(depth_var = c("x", "y", "z"),
                       title = c("Side View", "Front View", "Top View"))
  ggplot(gg_data, aes_string(x = plane[1], y = plane[2], color = plot_var), ...) +
    geom_point(alpha = 0.1, size = 0.5) +
    geom_smooth(method = "lm", formula = y ~ I(x^2) + x, color = "red") +
    geom_smooth(method = "lm", color = "red") +
    annotate("text", x = 0, y = 0, label = "origin", size = 5) +
    annotate("text", x = 0, y = 0,
             label = paste0("min_prob: ", round(min(pull(ungroup(gg_data), "min_freq")), 2))) +
    scale_color_continuous(guide = FALSE) +
    scale_x_continuous(filter(labels, var == plane[1])$label) +
    scale_y_continuous(filter(labels, var == plane[2])$label) +
    ggtitle(filter(titles, depth_var == depth)$title)
}

#' Plot a 3D image of a brain
#' @inheritParams rgl::plot3d
#' @export
#' @examples
#' file <- "~/Data/barresi/AT_1_Probabilities.h5"
#' \dontrun{
#' if (require(dplyr)) {
#'   tidy_brain <- file %>%
#'     read_h5() %>%
#'     tidy()
#'   plot3d(tidy_brain)
#' }
#' }

```

# Wild Type 
```{r}
ls_wt <- c("Wild Type_101", "Wild Type_102")
ls_wt

file_ls_wt =c("0")
file_ls_wt

for (i in (1:length(ls_wt))) {
  file_ls_wt[i] = paste("file", ls_wt[i])
}

file_ls_wt

file_ls_wt[1]<- "Sample/AT_wildtype_101_Probabilities.h5"
file_ls_wt[2] <-  "Sample/AT_wildtype_102_Probabilities.h5"
#file_ls[3] <-  "Sample/AT_wildtype_104_Probabilities.h5"



file_ls_wt

#defalt threshol = 0.9
tidy_brain_ls_wt <- list()
for (i in (1:length(ls_wt))) {
  tidy_brain_ls_wt[[i]] <- file_ls_wt[i] %>%
  read_h5() %>%
  tidy()
}
```


#You too
```{r}
#ls <- c("W_101", "W_102", "W_104", "You_Too_01", "You_Too_02", "You_Too_03", "You_Too_04","You_Too_06", "You_Too_21")

ls_youtoo <- c("You_Too_01", "You_Too_02")

file_ls_youtoo =c("0")
file_ls_youtoo

for (i in (1:length(ls_youtoo))) {
  file_ls_youtoo[i] = paste("file", ls_youtoo[i])
}

file_ls_youtoo

file_ls_youtoo[1] <- "Sample/AT_01_Probabilities.h5"
file_ls_youtoo[2] <- "Sample/AT_02_Probabilities.h5"
#file_ls[6] <- "Sample/AT_03_Probabilities.h5"
#file_ls[7] <- "Sample/AT_04_Probabilities.h5"
#file_ls[8] <- "Sample/AT_06_Probabilities.h5"
#file_ls[9] <- "Sample/AT_21_Probabilities.h5"


file_ls_youtoo
#threshold = 0.7
tidy_brain_ls_youtoo <- list()
for (i in (1:length(file_ls_youtoo))) {
  tidy_brain_ls_youtoo[[i]] <- file_ls_youtoo[i] %>%
  read_h5() %>%
  tidy(threshold=0.5)
}

```


# Investigate thresholds
```{r eval=FALSE, include=FALSE}
#Wild type threshold = 0
brain_ls_wt <- list()
for (i in (1:length(ls_wt))) {
  brain_ls_wt[[i]] <- file_ls_wt[i] %>%
  read_h5() %>%
  tidy(threshold=0)
}

#You too threshold = 0
brain_ls_youtoo <- list()
for (i in (1:length(file_ls_youtoo))) {
  brain_ls_youtoo[[i]] <- file_ls_youtoo[i] %>%
  read_h5() %>%
  tidy(threshold=0)
}


sample1<- brain_ls_wt[[1]]
sample3<- brain_ls_youtoo[[1]]

p1<-ggplot( data = sample1, aes(x = Freq)) + geom_density(adjust = 0.4) + labs(title = "Wild type sample 101") 
p2<-ggplot( data = sample3, aes(x = Freq)) + geom_density(adjust = 0.4) + labs(title = "You too sample 01") 
grid.arrange(p1,p2,ncol=1)
```


# Reorient
```{r}
#Wild Type
ro_brain_ls_wt<-tidy_brain_ls_wt%>%
lapply(reorient)

#You Too
ro_brain_ls_youtoo<-tidy_brain_ls_youtoo%>%
lapply(reorient)
```




# Test one plot
```{r}
plotlist <- list()
for (i in (4:4)){
  plotlist[[i]] <- plot2d(tidy_brain_ls[[i]], title=paste("Sample", ls[i]))
   # plot(plotlist[[i]])
   # dev.off
 # decorate3d
}

```

# All plots
```{r}
plotlist_wt <- list()
for (i in (1:length(ls_wt))){
  plotlist_wt[[i]] <- plot2d(ro_brain_ls_wt[[i]], title=paste("Sample", ls_wt[i]))
   # plot(plotlist[[i]])
   # dev.off
}

plotlist_youtoo <- list()
for (i in (1:length(ls_youtoo))){
  plotlist_youtoo[[i]] <- plot2d(ro_brain_ls_youtoo[[i]], title=paste("Sample", ls_youtoo[i]))
   # plot(plotlist[[i]])
   # dev.off
}
#do.call(grid.arrange, c(plotlist, ncol = 3))

```



