---
title: "Read h5"
author: "CZ"
date: "4/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#hdf5
```


#hdf5r
```{r}
library(hdf5r)
library(dplyr)
library(cranium)
library(broom)
library(tidyverse)
library(rgl)


file <- "AT_wildtype_101_Probabilities.h5"

#################
#function
read_h5 <- function(file, name = NULL, ...) {
  if("hdf5" %in% (.packages())){
    objs <- rhdf5::h5ls(file) %>%
      dplyr::filter(otype == "H5I_DATASET")
    if (is.null(name)) {
      # take the first HDF5 dataset
      name <- objs$name[1]
    }
    x <- rhdf5::h5read(file, name, ...)
    if (length(dim(x)) > 3) {
      # take the second image
      x <- x[2,,,]
    }
    class(x) <- append("brain", class(x))
    return(x)
  }
  if("hdf5r" %in% (.packages())){
    file.h5 <- H5File$new(file, mode="r")
    brain <- file.h5[["exported_data"]]
    x <- brain[2,,,]
  }
  class(x) <- append("brain", class(x))
  return(x)
}

tidy.brain <- function(x, threshold = 0.9, ...) {
  res <- x %>%
    as.data.frame.table() %>%
    mutate(x = as.integer(Var1) * 0.13,
           y = as.integer(Var2) * 0.13,
           z = as.integer(Var3) * 0.21) %>%
    select(x, y, z, Freq) %>%
    tibble::as_tibble() %>%
    mutate(gray_val = gray(1 - Freq)) %>%
    #    filter(Freq > 0) %>%
    filter(Freq > threshold)
  class(res) <- append("tbl_brain", class(res))
  return(res)
}


tidy_brain <- file %>%
  read_h5() %>%
  tidy()
###############

```

```{r}
plot3d_model(tidy_brain)
plot3d(tidy_brain)
```


#plot 3d
```{r}
#' Plot a 3D image of a brain
#' @inheritParams rgl::plot3d
#' @export
#' @examples
#' file <- "~/Data/barresi/AT_1_Probabilities.h5"
#' \dontrun{
#' if (require(dplyr)) {
#'   tidy_brain <- file %>%
#'     read_h5() %>%
#'     tidy()
#'   plot3d(tidy_brain)
#' }
#' }

plot3d.tbl_brain <- function(x, ...) {
  x_df <- as.data.frame(x)
  n <- nrow(x_df)
  message(paste("Will now plot", n, "points..."))
  if (n > 250000) {
    warning(paste("You are about to plot", n,
                  "points. Consider increasing the threshold parameter."))
  }
  rgl::plot3d(x_df, type = "p", alpha = x_df$Freq,
              #         width = 900, height = 800,
              xlab = "x", ylab = "y", zlab = "z",
              size = 2, col = x_df$gray_val, ...)
  #  plot3d_model(x_df)
}

#' @rdname plot3d.tbl_brain
#' @export
#' @examples
#' file <- "~/Data/barresi/AT_1_Probabilities.h5"
#' \dontrun{
#' brain <- read_h5(file)
#' plot3d(brain)
#' }


plot3d.brain <- function(x, ...) {
  tidy_brain <- tidy(x)
  return(plot3d(tidy_brain, ...))
}

#' @importFrom mosaic makeFun
#' @importFrom stats lm coef

plot3d_model <- function(xyz, ...) {
  mod_list <- get_jawbone(xyz)
  # quadratic plane
  plot3d(mod_list[[1]], alpha = 0.5, col = "dodgerblue",
         xlim = range(xyz$x), ylim = range(xyz$y), zlim = range(xyz$z),
         add = TRUE)
  
  # flat plane
  plot3d(mod_list[[2]], alpha = 0.5, col = "green",
         xlim = range(xyz$x), ylim = range(xyz$y), zlim = range(xyz$z),
         add = TRUE)
  
  # their intersection
  t <- seq(0, max(xyz$x))
  plot3d(mod_list[[3]](t), alpha = 0.5, col = "red", size = 5,
         xlim = range(xyz$x), ylim = range(xyz$y), zlim = range(xyz$z),
         add = TRUE)
  return(mod_list)
}


```


#read_h5
```{r}
read_h5 <- function(file, name = NULL, ...) {
  objs <- rhdf5::h5ls(file) %>%
    dplyr::filter(otype == "H5I_DATASET")
  if (is.null(name)) {
    # take the first HDF5 dataset
    name <- objs$name[1]
  }
  x <- rhdf5::h5read(file, name, ...)
  if (length(dim(x)) > 3) {
    # take the second image
    x <- x[2,,,]
  }
  else {
    file.h5 <- H5File$new(file, mode="r")
    brain <- file.h5[["exported_data"]]
    x <- brain[2,,,]
  }
  class(x) <- append("brain", class(x))
  return(x)
}

read_h5()
```

#tidy
```{r}

```
